apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-app
      version: v1.0.0
  template:
    metadata:
      labels:
        app: capstone-app
        version: v1.0.0
    spec:
      containers:
      - name: capstone-app
        image: cumong500/proj5:v1.0.0
        ports:
        - containerPort: 80